topbook/app/urls.py
from django.conf.urls import url
from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^book_search/$', views.book_search, name='book_search'),
    url(r'^pie_graph/$', views.pie_graph, name='pie_graph'),
    url(r'^bar_chart/$', views.bar_chart, name='bar_chart'),
    url(r'^bar_chart_2/$', views.bar_chart_2, name='bar_chart_2'),
    url(r'^publish_house_info_1/$', views.publish_house_info_1, name='publish_house_info_1'),
    url(r'^publish_house_info_2/$', views.publish_house_info_2, name='publish_house_info_2'),
    url(r'^publish_house_info_3/$', views.publish_house_info_3, name='publish_house_info_3'),
    url(r'^publish_search/$', views.publish_search, name='publish_search'),
    ]

topbook/topbook/urls.py
from django.urls import path
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^app/',include('app.urls')),
    url(r'^admin/',admin.site.urls),
]

topbook/app/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)
    score = models.CharField(max_length=32)
    img_src = models.CharField(max_length=64, null=True)
    publish_detail = models.CharField(max_length=255)
    slogan = models.CharField(max_length=255)
    publish_house = models.CharField(max_length=32, null=True)
    detail_addr = models.CharField(max_length=255, null=True)
    comment_people = models.CharField(max_length=32, null=True)
    publishing_house = models.ForeignKey(to="Publishing_house",to_field="nid",on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.title
    

class Publishing_house(models.Model):
    nid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name
    

topbook/app/views.py
from django.http import HttpResponse
from django.shortcuts import render

# 导入分页器
from django.core.paginator import Paginator,EmptyPage
# Create your views here.
from app.models import Book,Publishing_house

def publish_house_info_1(request):
    from django.db.models import Avg
    house_list = Publishing_house.objects.all().annotate(c=Avg("book__score")).order_by('-c')
    for house in house_list:
        print(house.name, '平均得分为：',house.c)

    paginator = Paginator(house_list, 6)
    current_page_num = int(request.GET.get("page", 1))

    if paginator.num_pages > 11:
        if current_page_num - 5 < 1:
            page_range = range(1,12)
        elif current_page_num + 5 > paginator.num_pages:
            page_range = range(paginator.num_pages-10,paginator.num_pages+1)
        else: 
            page_range = range(current_page_num-5,current_page_num+6)
    else:
        page_range = paginator.page_range

    try:
        current_page = paginator.page(current_page_num)  # 当前页
    except EmptyPage as e:
        current_page = paginator.page(1)
    return render(request, "app/publish_house_info_1.html", locals())

def publish_house_info_2(request):
    from django.db.models import Count
    from django.db.models import Sum
    house_list = Publishing_house.objects.all().annotate(c=Sum("book__comment_people")).order_by('-c')
    for house in house_list:
        house.c = int(house.c)
        print(house.name, '平均评价人次为：', house.c)

    paginator = Paginator(house_list, 6)
    current_page_num = int(request.GET.get("page", 1))

    if paginator.num_pages > 11:
        if current_page_num - 5 < 1:
            page_range = range(1,12)
        elif current_page_num + 5 > paginator.num_pages:
            page_range = range(paginator.num_pages-10,paginator.num_pages+1)
        else: 
            page_range = range(current_page_num-5,current_page_num+6)
    else:
        page_range = paginator.page_range

    try:
        current_page = paginator.page(current_page_num)  # 当前页
    except EmptyPage as e:
        current_page = paginator.page(1)
    return render(request, "app/publish_house_info_2.html", locals())

def publish_house_info_3(request):
    from django.db.models import Count
    house_list = Publishing_house.objects.all().annotate(c=Count("book__title")).order_by('-c')

    paginator = Paginator(house_list, 6)
    current_page_num = int(request.GET.get("page", 1))

    if paginator.num_pages > 11:
        if current_page_num - 5 < 1:
            page_range = range(1,12)
        elif current_page_num + 5 > paginator.num_pages:
            page_range = range(paginator.num_pages-10,paginator.num_pages+1)
        else: 
            page_range = range(current_page_num-5,current_page_num+6)
    else:
        page_range = paginator.page_range

    try:
        current_page = paginator.page(current_page_num)  # 当前页
    except EmptyPage as e:
        current_page = paginator.page(1)
    return render(request, "app/publish_house_info_3.html", locals())

def publish_search(request):
    from django.db.models import Count
    if request.method == 'POST':
        housename = request.POST.get('housename')
        house_get = Publishing_house.objects.filter(name=housename).first()
        book_list = house_get.book_set.all()   
        if house_get:
            return render(request,"app/publish_search.html",{'house':house_get, 'book_list':book_list})
        else:
            notfound = '没找到...  试试查找别的出版社吧（‐＾▽＾‐）'
            return render(request,"app/publish_search.html",{'notfound':notfound})
    else:
        notfound = '请输入出版社名称...'
        return render(request,"app/publish_search.html",{'notfound':notfound})    


def bar_chart(request):
    print('柱状图信息：')
    from django.db.models import Count
    book_num = Publishing_house.objects.all().annotate(c=Count("book__title")).order_by('-c')
    for i in range(11):
        print(book_num[i].name, '共',book_num[i].c,'本书')
    return render(request, "app/bar_chart.html", {})

def bar_chart_2(request):
    print('柱状图信息：')
    from django.db.models import Count
    from django.db.models import Avg 
    book_num = Publishing_house.objects.all().annotate(c=Count("book__title")).order_by('-c')
    for i in range(11):
        score_avg = Book.objects.filter(publish_house=book_num[i].name).aggregate(c=Avg("score"))
        print(book_num[i].name, '共',book_num[i].c,'本书', '平均得分为：',score_avg)
    return render(request, "app/bar_chart_2.html", {})

def pie_graph(request):
    print('饼状图信息:')
    book_list = Book.objects.all()
    num = 0
    for book in book_list:
        num = num + int(book.comment_people)
    print('总评价人次:',num)
    from django.db.models import Avg    
    from django.db.models import Count
    book_num = Publishing_house.objects.all().annotate(c=Count("book__title")).order_by('-c')
    for i in range(5):
        score_avg = Book.objects.filter(publish_house=book_num[i].name).aggregate(c=Avg("score"))
        ordered_book = Book.objects.filter(publish_house=book_num[i].name).aggregate(x=Avg("comment_people"))
        print(book_num[i].name, '共',book_num[i].c,'本书', '平均分:',score_avg, '总评价人次：', ordered_book['x']*book_num[i].c)

    return render(request, "app/pie_graph.html", {})

def book_search(request):
    if request.method == 'POST':
        bookname = request.POST.get('bookname')
        # book_list = Book.objects.all()
        book_get = Book.objects.filter(title=bookname).first()
        if book_get:
            return render(request,"app/book_search.html",{'book':book_get})
        else:
            notfound = '没找到...  试试查找别的书籍吧（‐＾▽＾‐）'
            return render(request,"app/book_search.html",{'notfound':notfound})
    else:
        notfound = '请输入书籍名称...'
        return render(request,"app/book_search.html",{'notfound':notfound})    



def index(request):

    book_list = Book.objects.all()

    paginator = Paginator(book_list, 6)

    current_page_num = int(request.GET.get("page", 1))

    if paginator.num_pages > 11:
        if current_page_num - 5 < 1:
            page_range = range(1,12)
        elif current_page_num + 5 > paginator.num_pages:
            page_range = range(paginator.num_pages-10,paginator.num_pages+1)
        else: 
            page_range = range(current_page_num-5,current_page_num+6)
    else:
        page_range = paginator.page_range

    try:

        current_page = paginator.page(current_page_num)  # 当前页

    except EmptyPage as e:
        current_page = paginator.page(1)

    return render(request,"app/index.html",locals())

topbook/templates/app/bar_chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
<script>
    (function (){

    window.addEventListener("load", function(){

    var data = [40, 24, 20, 14, 14, 11, 10, 8, 6, 5, 5];
    var xinforma = ['人民文学出版社','上海译文出版社','生活.读书.新知三联书店','译林出版社','南海出版公司','北京十月文艺出版社','广西师范大学出版社','上海人民出版社','哈尔滨出版社','中华书局','作家出版社'];

    // 获取上下文
    var a_canvas = document.getElementById('a_canvas');
    var context = a_canvas.getContext("2d");


    // 绘制背景
    var gradient = context.createLinearGradient(0,0,0,300);


    gradient.addColorStop(0,"#e0e0e0");
    gradient.addColorStop(1,"#ffffff");


    context.fillStyle = gradient;

    context.fillRect(0,0,a_canvas.width,a_canvas.height);

    var realheight = a_canvas.height-15;
    var realwidth = a_canvas.width-40;
    // 描绘边框
    var grid_cols = data.length + 1;
    var grid_rows = 4;
    var cell_height = realheight / grid_rows;
    var cell_width = realwidth / grid_cols;
    context.lineWidth = 1;
    context.strokeStyle = "#a0a0a0";

    // 结束边框描绘
    context.beginPath();
    // 准备画横线
    /*for(var row = 1; row <= grid_rows; row++){
    var y = row * cell_height;
    context.moveTo(0,y);
    context.lineTo(a_canvas.width, y);
    }*/

    //划横线
    context.moveTo(10,realheight);
    context.lineTo(realwidth,realheight);


    //画竖线
    context.moveTo(10,10);
    context.lineTo(10,realheight);
    context.lineWidth = 1;
    context.strokeStyle = "black";
    context.stroke();


    var max_v =0;

    for(var i = 0; i<data.length; i++){
    if (data[i] > max_v) { max_v =data[i]};
    }
    max_v = max_v * 1.1;
    // 将数据换算为坐标
    var points = [];
    for( var i=0; i < data.length; i++){
    var v= data[i];
    var px = cell_width *　(i +1);
    var py = realheight - realheight*(v / max_v);
    //alert(py);
    points.push({"x":px,"y":py});
    }

    //绘制坐标图形
    for(var i in points){
    var p = points[i];
    context.beginPath();
    context.fillStyle="green";
    context.fillRect(p.x,p.y,15,realheight-p.y);

    context.fill();
    }
    //添加文字
    for(var i in points)
    {  var p = points[i];
    context.beginPath();
    context.fillStyle="black";
    context.font = 'bold 11px 微软雅黑';
    context.fillText(data[i], p.x + 1, p.y - 15);
    context.fillText(xinforma[i],p.x + 2,realheight+12);
    context.fillText('出版社',realwidth,realheight+12);
    }
    },false);
    })();

</script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container-fluid">
            <div>
                <form class="navbar-form navbar-right"  method="POST" action="{% url 'app:book_search' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search Book" name="bookname">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
            </div>
            <div class="navbar-header">
                <a class="navbar-brand" href={% url 'app:index' %}>APP主页</a> 
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href={% url 'app:pie_graph' %}>饼状图</a></li>
                    <li class="dropdown active">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            柱状图
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:bar_chart' %}>柱状图一</a></li>
                            <li><a href={% url 'app:bar_chart_2' %}>柱状图二</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            出版社排行
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:publish_house_info_1' %}>所获评分最高</a></li>
                            <li><a href={% url 'app:publish_house_info_2' %}>评价人次最多</a></li>
                            <li><a href={% url 'app:publish_house_info_3' %}>出版优秀图书最多</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br/><br/>
    <div>
        <h3>上榜图书数量</h3>
        <canvas id="a_canvas" width="1500" height="700">
        浏览器不支持canvas
        </canvas><br/><br/><br/><br/><br/><br/>
    </div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</body>
</html>

topbook/templates/app/bar_chart_2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
<script>
    (function (){

    window.addEventListener("load", function(){

    var data = [935, 883, 955, 921, 800, 945, 930, 1000, 816, 1300, 880];
    var xinforma = ['人民文学出版社','上海译文出版社','生活.读书.新知三联书店','译林出版社','南海出版公司','北京十月文艺出版社','广西师范大学出版社','上海人民出版社','哈尔滨出版社','中华书局','作家出版社'];

    // 获取上下文
    var a_canvas = document.getElementById('a_canvas');
    var context = a_canvas.getContext("2d");


    // 绘制背景
    var gradient = context.createLinearGradient(0,0,0,300);


    gradient.addColorStop(0,"#e0e0e0");
    gradient.addColorStop(1,"#ffffff");


    context.fillStyle = gradient;

    context.fillRect(0,0,a_canvas.width,a_canvas.height);

    var realheight = a_canvas.height-15;
    var realwidth = a_canvas.width-40;
    // 描绘边框
    var grid_cols = data.length + 1;
    var grid_rows = 4;
    var cell_height = realheight / grid_rows;
    var cell_width = realwidth / grid_cols;
    context.lineWidth = 1;
    context.strokeStyle = "#a0a0a0";

    // 结束边框描绘
    context.beginPath();
    // 准备画横线
    /*for(var row = 1; row <= grid_rows; row++){
    var y = row * cell_height;
    context.moveTo(0,y);
    context.lineTo(a_canvas.width, y);
    }*/

    //划横线
    context.moveTo(10,realheight);
    context.lineTo(realwidth,realheight);


    //画竖线
    context.moveTo(10,10);
    context.lineTo(10,realheight);
    context.lineWidth = 1;
    context.strokeStyle = "black";
    context.stroke();


    var max_v =0;

    for(var i = 0; i<data.length; i++){
    if (data[i] > max_v) { max_v =data[i]};
    }
    max_v = max_v * 1.1;
    // 将数据换算为坐标
    var points = [];
    for( var i=0; i < data.length; i++){
    var v= data[i];
    var px = cell_width *　(i +1);
    var py = realheight - realheight*(v / max_v);
    //alert(py);
    points.push({"x":px,"y":py});
    }

    //绘制坐标图形
    for(var i in points){
    var p = points[i];
    context.beginPath();
    context.fillStyle="green";
    context.fillRect(p.x,p.y,15,realheight-p.y);

    context.fill();
    }
    //添加文字
    for(var i in points)
    {  var p = points[i];
    context.beginPath();
    context.fillStyle="black";
    context.fillText(data[i], p.x + 1, p.y - 15);
    context.fillText(xinforma[i],p.x + 2,realheight+12);    
    }
    },false);
    })();

</script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container-fluid">
            <div>
                <form class="navbar-form navbar-right"  method="POST" action="{% url 'app:book_search' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search Book" name="bookname">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
            </div>
            <div class="navbar-header">
                <a class="navbar-brand" href={% url 'app:index' %}>APP主页</a> 
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href={% url 'app:pie_graph' %}>饼状图</a></li>
                    <li class="dropdown active">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            柱状图
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:bar_chart' %}>柱状图一</a></li>
                            <li><a href={% url 'app:bar_chart_2' %}>柱状图二</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            出版社排行
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:publish_house_info_1' %}>所获评分最高</a></li>
                            <li><a href={% url 'app:publish_house_info_2' %}>评价人次最多</a></li>
                            <li><a href={% url 'app:publish_house_info_3' %}>出版优秀图书最多</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br/><br/>
    <div>
        <h3>各个出版社图书评价得分</h3><h4>（单位：0.001）</h4>
        <canvas id="a_canvas" width="1400" height="650">
        浏览器不支持canvas
        </canvas><br/><br/><br/><br/><br/><br/>
    </div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</body>
</html>

topbook/templates/app/book_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-inverse" role="navigation" >
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href={% url 'app:index' %}>APP主页</a> 
        </div>
        <div>
            <form class="navbar-form navbar-right"  method="POST" action="{% url 'app:book_search' %}">
            {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search Book" name="bookname">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href={% url 'app:pie_graph' %}>饼状图</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            柱状图
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:bar_chart' %}>柱状图一</a></li>
                            <li><a href={% url 'app:bar_chart_2' %}>柱状图二</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            出版社排行
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:publish_house_info_1' %}>所获评分最高</a></li>
                            <li><a href={% url 'app:publish_house_info_2' %}>评价人次最多</a></li>
                            <li><a href={% url 'app:publish_house_info_3' %}>出版优秀图书最多</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
    {% if notfound %}
        <h2 align='center'>{{notfound}}</h2>
    {% else %}
        <table width="100%">
        <tbody>
            <tr class="item">
                <td width="100" valign="top">
                    <img src={{book.img_src}}>
                </td>
                <td valign="top">
                    <ul class="list-group">
                        <li class="list-group-item"> 
                            <h2>{{book.title}}</h2>
                            <p>
                                <h3>豆瓣得分：{{ book.score }}</h3><h4>({{book.comment_people}}评价)</h4>
                                <h3>{{ book.publish_detail }}</h3><br/>
                                <h3><span class="glyphicon glyphicon-star">{{book.slogan}}</span></h3><br/>
                                <a href={{book.detail_addr}} class="btn btn-primary">访问详情</a>
                            </p>
                        </li>
                    </ul>
                </td>
            </tr>
        </tbody>
        </table>
    {% endif %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script> 
</body>
</html>

topbook/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>豆瓣图书TOP250</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    </head>
<body>
<nav class="navbar navbar-inverse" role="navigation" >
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href={% url 'app:index' %}>APP主页</a> 
        </div>
        <div>
            <form class="navbar-form navbar-right"  method="POST" action="{% url 'app:book_search' %}">
            {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search Book" name="bookname">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href={% url 'app:pie_graph' %}>饼状图</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            柱状图
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:bar_chart' %}>柱状图一</a></li>
                            <li><a href={% url 'app:bar_chart_2' %}>柱状图二</a></li>
                        </ul>
                    </li>
                    {% comment %} <li><a href={% url 'app:bar_chart' %}>柱状图</a></li> {% endcomment %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            出版社排行
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:publish_house_info_1' %}>所获评分最高</a></li>
                            <li><a href={% url 'app:publish_house_info_2' %}>评价人次最多</a></li>
                            <li><a href={% url 'app:publish_house_info_3' %}>出版优秀图书最多</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<h1 style='title' align='center'>豆瓣图书榜TOP250</h1><br/>
    <div class='container'>
        <div class='row'>
            {% for book in current_page %}
            <div class='col-sm-4'>
                <div class='card', style='width: 50rem; height: 60rem;'>
                    <img class='card-img-top' src={{book.img_src}} alt='Card image cap'>
                    <div class='card body'>
                        <h5 class='card-title'>{{book.title}}</h5>
                        <p class='card-text'>
                            豆瓣得分：{{ book.score }}<br/>
                            {{ book.publish_detail }}<br/>
                            <span class="glyphicon glyphicon-star">{{book.slogan}}</span><br/>
                            <a href={{book.detail_addr}} class="btn btn-primary">访问详情</a>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
<nav aria-label="Page navigation" align='center'>
    <ul class="pagination">
        {% if current_page.has_previous %}
            <li>
                <a href="?page={{ current_page.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">上一页</span>
                </a>
            </li>
        {% else %}
            <li class="disabled">
                <a href="" aria-label="Previous">
                    <span aria-hidden="true">上一页</span>
                </a>
            </li>
        {% endif %}

        {% for item in page_range %}
            {% if current_page_num == item %}
                <li class="active" ><a href="?page={{ item }}">{{ item }}</a></li>
            {% else %}
                <li><a href="?page={{ item }}">{{ item }}</a></li>
            {% endif %}
        {% endfor %}


        {% if current_page.has_next %}
            <li><a href="?page={{ current_page.next_page_number }}" aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
        {% else %}
            <li class="disabled"><a href="" aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
        {% endif %}
    </ul>
</nav>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script> 
</body>
</html>

topbook/templates/app/publish_house_info_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>豆瓣图书TOP250</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    </head>
<body>
<nav class="navbar navbar-inverse" role="navigation" >
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href={% url 'app:index' %}>APP主页</a> 
        </div>
        <div>
            <form class="navbar-form navbar-right"  method="POST" action="{% url 'app:publish_search' %}">
            {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search Publishing House" name="housename">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href={% url 'app:pie_graph' %}>饼状图</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            柱状图
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:bar_chart' %}>柱状图一</a></li>
                            <li><a href={% url 'app:bar_chart_2' %}>柱状图二</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            出版社排行
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'app:publish_house_info_1' %}>所获评分最高</a></li>
                            <li><a href={% url 'app:publish_house_info_2' %}>评价人次最多</a></li>
                            <li><a href={% url 'app:publish_house_info_3' %}>出版优秀图书最多</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<h1 style='title' align='center'>出版社信息(按出版优秀图书数量排序)</h1><br/>
    <div class='container'>
        <div class='row'>
            {% for house in current_page %}
            <div class='col-sm-4'>
                <div class='card', style='width: 20rem; height: 10rem;'>
                    <div class='card body'>
                        <h3 class='card-title'>{{house.name}}</h3>
                        <p class='card-text'>
                            平均评分为：{{ house.c }}<br/>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
<nav aria-label="Page navigation" align='center'>
    <ul class="pagination">
        {% if current_page.has_previous %}
            <li>
                <a href="?page={{ current_page.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">上一页</span>
                </a>
            </li>
        {% else %}
            <li class="disabled">
                <a href="" aria-label="Previous">
                    <span aria-hidden="true">上一页</span>
                </a>
            </li>
        {% endif %}

        {% for item in page_range %}
            {% if current_page_num == item %}
                <li class="active" ><a href="?page={{ item }}">{{ item }}</a></li>
            {% else %}
                <li><a href="?page={{ item }}">{{ item }}</a></li>
            {% endif %}
        {% endfor %}


        {% if current_page.has_next %}
            <li><a href="?page={{ current_page.next_page_number }}" aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
        {% else %}
            <li class="disabled"><a href="" aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
        {% endif %}
    </ul>
</nav>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script> 
</body>
</html>